### PR TITLE
NCEO biomass dataset discovery example

### PR DESCRIPTION
**Pull request by kathrynberger**
Developed a notebook for dataset for discovery:

Case Study focused on Guinea and conservation, using the [NCEO Biomass 2017 Africa dataset](http://veda-staging-stac-browser.s3-website-us-west-2.amazonaws.com/collections/nceo_africa_2017).

Explored the 2017 dataset, ran zonal statistics and displayed the results on a choropleth map using the following approach:

   1. Query STAC API and explore item contents for a given collection
   2. Read and access the data 
   3. Visualize the collection with `hvplot`
   4. Run zonal statistics on collection using `rasterstats`
   5. Visualize resultant zonal statistics on a choropleth map

related to: https://github.com/NASA-IMPACT/veda-analytics/issues/35

cc' @jsignell @j08lue

### CODE REVIEW

**Review by jsignell — COMMENTED** [review]
This looks really good to me! I just have a few suggestions and a note the the "Run in " link should point to the 2i2c hub rather than binder. There are instructions for how to generate a link here: https://nasa-impact.github.io/veda-docs/example-notebooks/ but also you can just copy the block from one of the existing notebooks and sub in your notebook name.

**Comment by jsignell** [comment]
Just one more note. I tried running this on 2i2c and the read worked fine with just 
```python
gdal_env = stackstac.DEFAULT_GDAL_ENV.updated(always=dict(session=rio.session.AWSSession(boto3.Session())))
```

**Comment by kathrynberger** [comment]
> Just one more note. I tried running this on 2i2c and the read worked fine with just
> 
> ```python
> gdal_env = stackstac.DEFAULT_GDAL_ENV.updated(always=dict(session=rio.session.AWSSession(boto3.Session())))
> ```

This is good to hear. It was the only way that worked on my machine, pairing with Vincent to trouble-shoot it. I can try removing the `no sign in request` component and re-running it to see if it still works (and there wasn't something else confounding things earlier on).

**Comment by jsignell** [comment]
> It was the only way that worked on my machine

I think we should be running these on the 2i2c hub.

**Comment by kathrynberger** [comment]
> > It was the only way that worked on my machine
> 
> I think we should be running these on the 2i2c hub.

That was a typo on my part. What I meant to say, when running this on my access to the `2i2c` hub (not local machine) I ran into a number of admin access issues which were strange. I'm not sure if there were other confounding factors, but the `no sign in request` route was the only one that worked. That being said, I've just removed that line component from the line, refreshed the kernel, and have no issues. I'll revise and we should be sorted 👍

**Comment by kathrynberger** [comment]
> This looks really good to me! I just have a few suggestions and a note the the "Run in " link should point to the 2i2c hub rather than binder. There are instructions for how to generate a link here: https://nasa-impact.github.io/veda-docs/example-notebooks/ but also you can just copy the block from one of the existing notebooks and sub in your notebook name.

Just thinking about this now @jsignell and should this have a Binder link at all? It's required to be run on `2i2c`

**Comment by kathrynberger** [comment]
> > > It was the only way that worked on my machine
> > 
> > 
> > I think we should be running these on the 2i2c hub.
> 
> That was a typo on my part. What I meant to say, when running this on my access to the `2i2c` hub (not local machine) I ran into a number of admin access issues which were strange. I'm not sure if there were other confounding factors, but the `no sign in request` route was the only one that worked. That being said, I've just removed that line component from the line, refreshed the kernel, and have no issues. I'll revise and we should be sorted 👍

Sorry, I spoke too soon. Accessing the data worked just fine, _visualizing_ the data with `hvplot` gives an `access denied` without the extra line.

**Comment by jsignell** [comment]
> > > > It was the only way that worked on my machine
> > > 
> > > 
> > > I think we should be running these on the 2i2c hub.
> > 
> > 
> > That was a typo on my part. What I meant to say, when running this on my access to the `2i2c` hub (not local machine) I ran into a number of admin access issues which were strange. I'm not sure if there were other confounding factors, but the `no sign in request` route was the only one that worked. That being said, I've just removed that line component from the line, refreshed the kernel, and have no issues. I'll revise and we should be sorted +1
> 
> Sorry, I spoke too soon. Accessing the data worked just fine, _visualizing_ the data with `hvplot` gives an `access denied` without the extra line. This is still an issue.

YES ok I see it now as well. Right the load doesn't happen until that line. I forgot and had undersized my server so it ran out of memory before I got to the failure. I am on the same page now. Sorry for the noise.

**Comment by kathrynberger** [comment]
I've made the revisions requested, including removing the `binder` link and replacing it with the VEDA Jupyter Hub 2i2c information/instructions. I've also kept in the line regarding the `no sign in request` with AWS as that is the only (current) way I've found to visualize the dataset.

**Pull request merged**
