### PR TITLE
Feat/add mapping fires 2

### PR DESCRIPTION
**Pull request by abarciauskas-bgse**
This PR renames the wfs notebook and adds it to the TOC

@mccabete how does this look to you? You can check it out via the preview: https://nasa-impact.github.io/veda-docs/pr-preview/pr-79/notebooks/tutorials/mapping_fires.html

### CODE REVIEW

**Comment by j08lue** [comment]
Kindly asking @jsignell to review in my place.

**Comment by mccabete** [comment]
@abarciauskas-bgse this looks fine. There are a few changes that I think got lost in the file restructuring, but I can add them either here or after the merge.

**Comment by mccabete** [comment]
Added those changes to #80

**Comment by jsignell** [comment]
This looks broadly good! I think some things just got a little lost in the merges. I am fixing a typo and the binder link now and will push to this PR.

**Review by jsignell — APPROVED** [review]
LGTM!

**Comment by jsignell** [comment]
Ok I just read through and re-executed the notebook to make double sure that Tess's changes made it in. I am going to merge when this is green, but just shout if something is missing :)

**Comment by mccabete** [comment]
Thanks Julia!
________________________________

**Pull request merged**
