### PR TITLE
Add VEDA Search API with `intake` Notebook

### PR DESCRIPTION
**Pull request by ranchodeluxe**
This notebook shows how we can use VEDA Search API with `intake-stac` and `intake-xarray` for loading and inspecting. It's pretty rudimentary. Let me know if you'd like more processing examples included

Ticket: https://github.com/NASA-IMPACT/veda-architecture/issues/148

SCME Notebook to test: https://daskhub.veda.smce.nasa.gov/hub/user-redirect/lab/tree/gcorradini/scratch_w_auth.ipynb

### CODE REVIEW

**Comment by ranchodeluxe** [comment]
@j08lue: the last AC on the ticket (https://github.com/NASA-IMPACT/veda-architecture/issues/148) is about getting science users to see if this notebook example is helpful. Sounds like you have ideas on who to contact about that?

**Comment by abarciauskas-bgse** [comment]
@ranchodeluxe thanks for opening this PR, great work!

A few comments that I think will help users run this outside of the SMCE daskhub:

1. Can we add the intake-stac requirement to requirements.txt? I had issues running the notebook at first because I think there can be a conflict if you have intake installed and _not_ intake-stac. I had to uninstall intake and just install intake-stac. cognito_ client is in requirements.txt so you may even be able to remove that installation line. I'm hoping if people create an environment from requirements.txt the notebooks will run smoothly (assuming access is configured)
2. I had to create a rasterio session with the following code:

```
from rasterio.session import AWSSession
import os

session = boto3.Session(aws_access_key_id=creds['AccessKeyId'], 
                        aws_secret_access_key=creds['SecretKey'],
                        aws_session_token=creds['SessionToken'],
                        region_name='us-west-2')

rio_env = rio.Env(AWSSession(session),
                  GDAL_DISABLE_READDIR_ON_OPEN='EMPTY_DIR',
                  GDAL_HTTP_COOKIEFILE=os.path.expanduser('~/cookies.txt'),
                  GDAL_HTTP_COOKIEJAR=os.path.expanduser('~/cookies.txt'))
rio_env.__enter__()
```

before calls to `rio.open`

3. This could be for a future PR or debatable depending on what the user prefers: but I think I would remove the instruction about using STAC browser for bounding boxes and datetimes. For bounding boxes different python mapping lib like ipyleaflet to instruct users about how to draw a bounding box and get the coordinates back. For timeseries I would probably just rely on the users to be able to generate a valid datetime string.


I think we should get some science user feedback on this and then we could maybe iterate on the instructional text based off their feedback.

@j08lue should we ask @ashiklom for someone to review this notebook?

**Comment by ranchodeluxe** [comment]
>     1. Can we add the intake-stac requirement to requirements.txt? I had issues running the notebook at first because I think there can be a conflict if you have intake installed and _not_ intake-stac. I had to uninstall intake and just install intake-stac. cognito_ client is in requirements.txt so you may even be able to remove that installation line. I'm hoping if people create an environment from requirements.txt the notebooks will run smoothly (assuming access is configured)
> 
>     2. I had to create a rasterio session with the following code:
> 
> 
> ```
> from rasterio.session import AWSSession
> import os
> 
> session = boto3.Session(aws_access_key_id=creds['AccessKeyId'], 
>                         aws_secret_access_key=creds['SecretKey'],
>                         aws_session_token=creds['SessionToken'],
>                         region_name='us-west-2')
> 
> rio_env = rio.Env(AWSSession(session),
>                   GDAL_DISABLE_READDIR_ON_OPEN='EMPTY_DIR',
>                   GDAL_HTTP_COOKIEFILE=os.path.expanduser('~/cookies.txt'),
>                   GDAL_HTTP_COOKIEJAR=os.path.expanduser('~/cookies.txt'))
> rio_env.__enter__()
> ```
> 
> before calls to `rio.open`
> 
>     3. This could be for a future PR or debatable depending on what the user prefers: but I think I would remove the instruction about using STAC browser for bounding boxes and datetimes. For bounding boxes different python mapping lib like ipyleaflet to instruct users about how to draw a bounding box and get the coordinates back. For timeseries I would probably just rely on the users to be able to generate a valid datetime string.
> 
> 

@abarciauskas-bgse : I've made the above changes and here is the new notebook. I'll reach out the folks Jonas supplied today to get feedback: https://daskhub.veda.smce.nasa.gov/hub/user-redirect/lab/tree/gcorradini/veda_search_api_w_intake_v2.ipynb

**Comment by ranchodeluxe** [comment]
@abarciauskas-bgse: I'm gonna need to merge the newest version so I can get feedback. I erroneously attempted them to run the Jupyter notebook but the fact that the server doesn't stay up is a problem. We good to merge?

**Comment by abarciauskas-bgse** [comment]
@ranchodeluxe go for it - you won't see the notebook in the navigation but that's ok it should still be accessible via URL

**Pull request merged**
