### PR TITLE
Add notebooks showing how to set up STAC objects

### PR DESCRIPTION
**Pull request by jsignell**
Not sure if we want to reference these yet from the table of contents but moving them over to docs in the interest of consolidation

### CODE REVIEW

**Review by j08lue — CHANGES_REQUESTED** [review]
The notebooks on how to create and validate STAC metadata are great and will be very helpful for our users. Nice that they include the VEDA-specific fields.

A small change: Instead of including a sample GeoTIFF with this repo, we can perhaps just create a dummy COG with random data from code. Just grab the `rasterio.Dataset.profile` from the sample file and store it in code, perhaps.

NetCDF to COG conversion is definitely something to include in our docs, but not with this code, please. Let us rather include a nice example that uses `rio-xarray`. There should be one ready soon from the CMIP6 conversion.

So, could we please skip the NetCDF to COG conversion for now and just publish the STAC notebooks? We should probably link to them from the other [docs on Catalog Ingestion](https://nasa-impact.github.io/veda-docs/contributing/dataset-ingestion/catalog-ingestion.html), too.

**Comment by jsignell** [comment]
> 



> The notebooks on how to create and validate STAC metadata are great and will be very helpful for our users. Nice that they include the VEDA-specific fields.
> 
> A small change: Instead of including a sample GeoTIFF with this repo, we can perhaps just create a dummy COG with random data from code. Just grab the `rasterio.Dataset.profile` from the sample file and store it in code, perhaps.


Yep sounds good! I'll make that change.

> NetCDF to COG conversion is definitely something to include in our docs, but not with this code, please. Let us rather include a nice example that uses `rio-xarray`. There should be one ready soon from the CMIP6 conversion.

Yeah it was much less clear how that notebook should work. If CMIP6 is a better example I am all for it.

> So, could we please skip the NetCDF to COG conversion for now and just publish the STAC notebooks? 

:+1:

> We should probably link to them from the other [docs on Catalog Ingestion](https://nasa-impact.github.io/veda-docs/contributing/dataset-ingestion/catalog-ingestion.html), too.

Exactly! Ok I'll make those changes.

@j08lue or @ividito if we are ready to publish these notebooks what should be the call to action at the end? I was thinking open a PR on veda-data, but are we ready to make that repo public?

**Review by ividito — APPROVED** [review]

**Comment by ividito** [comment]
> It looks to me like `veda-data` has been populated with all the relevant data, including the ingest issue template, from `veda-data-pipelines`. I just added a docs link to the README as well. So, to me, this can go public and become our official place to open ingest request tickets. @ividito, do you agree?

Yes, there's still some ongoing work to do but I think that repo will be where we want to collect new ingestion requests.

**Comment by jsignell** [comment]
Great! I'll just update the links on the veda-data side to reflect the mild reorg.

**Comment by j08lue** [comment]
Thanks for being so accepting of my "mild reorg", @jsignell. 😄 And for fixing it up.

**Pull request merged**
