### PR TITLE
Tidy up existing notebooks and make them more uniform

### PR DESCRIPTION
**Pull request by jsignell**
Closes https://github.com/NASA-IMPACT/veda-analytics/issues/3, #4

## Notes
I am kind of thinking of these notebooks in two groups, one is just using APIs directly ( timeseries-stac-api, hls-visualization ) and the other is using more python-centric tools. My leaning is to leave these as separate approaches and not try to use `pystac` in the API notebooks.

## To Do
I still have to finish on:
- [ ] ~~Generate GIFs~~ see question below
- [x] Visualizing Zarr
- [x] Searching VEDA STAC API and inspecting catalogs with intake

### CODE REVIEW

**Comment by jsignell** [comment]
Should the notebooks that I commit to this repo have rendered output?

**Comment by abarciauskas-bgse** [comment]
@jsignell Usually I run the notebooks locally, so the content of the `.ipynb` has the output of the cells and then when I call `render --to html` the html versions include some of the outputs. In many cases, I think it's better to have the output in the rendered versions. The images are compelling and helpful and even the less-graphical output of things like xarray and plain python objects can be helpful to someone just viewing the static content to understand the intent. Do you think it's possible to keep more of that content in the rendered html?

**Comment by jsignell** [comment]
> I think it's better to have the output in the rendered versions. 

Oh yes I totally agree with that. I have normally found it easier to keep track of real changes in git when the output is not stored in the cells, but I don't feel super strongly about it.

> Do you think it's possible to keep more of that content in the rendered html

I think in an ideal world the notebooks would be stored unrendered and there would be a CI/CD job that kicked off rendering and converting them all the html. But I'm fine working in the world that we have :)

**Comment by abarciauskas-bgse** [comment]
@jsignell we should totally move it to a CI/CD job - I think we would just have to skip any notebooks which requires data access (or setup credentials for the github runner) and any notebooks which are prohibitively long to run (gif generation, for example).

**Comment by jsignell** [comment]
> @jsignell we should totally move it to a CI/CD job - I think we would just have to skip any notebooks which requires data access (or setup credentials for the github runner) and any notebooks which are prohibitively long to run (gif generation, for example).

Ok great! My preference is definitely for setting up credentials in github. I rendered all the notebooks in this PR so should be good to go here. We can tackle the automatic running separately.

**Comment by j08lue** [comment]
How about this notebook, @abarciauskas-bgse and @jsignell? https://github.com/NASA-IMPACT/veda-documentation/blob/main/single-item-viz.ipynb 

We currently use it as reference for the NO2 data visualization/exploration, so it would be great to move it to the new repo. Maybe name it `no2-single-item-vizualization.ipynb`. 

I will move it over but to a separate branch for now, so I do not interfere with your work here. I created a PR against your branch here, feel free to triage.

**Comment by jsignell** [comment]
> How about this notebook, @abarciauskas-bgse and @jsignell? https://github.com/NASA-IMPACT/veda-documentation/blob/main/single-item-viz.ipynb
> 
> We currently use it as reference for the NO2 data visualization/exploration, so it would be great to move it to the new repo. Maybe name it `no2-single-item-vizualization.ipynb`.
> 
> I will move it over but to a separate branch for now, so I do not interfere with your work here. I created a PR against your branch here, feel free to triage.

Oh! Thanks Jonas! I think I missed that one as kind of a duplicate of open-and-plot before I understood that we are trying to capture the pythonic as well as the API-centric approaches.

**Comment by j08lue** [comment]
> I missed that one as kind of a duplicate of open-and-plot before I understood that we are trying to capture the pythonic as well as the API-centric approaches.

I do not have any opinion on how the notebook does things - we just need it because we want some docs on how to use the NO2 dataset.

**Comment by j08lue** [comment]
You could move the gif generation notebook (and its dependencies) into a subfolder `fancy-stuff` or so. Then people do not stumble over that on the look-out for basic examples.

**Comment by j08lue** [comment]
The new format for the notebooks is very nice and clean and the Binderhub links are a great option for users who view the notebooks statically somewhere. 😍

**Comment by jsignell** [comment]
Yeah I think I am struggling a bit with the dual purposes of these notebooks:

1) to demonstrate general approaches for using STAC
2) to demonstrate how to use particular datasets

**Comment by jsignell** [comment]
I feel like there should be a label system that we can use to dynamically create lists of notebooks.

**Comment by j08lue** [comment]
> I feel like there should be a label system that we can use to dynamically create lists of notebooks.

Yes, that would be a great solution to that valid problem. Let us keep this for later and ask our users how they would find relevant resources for their problem - be that technical or dataset-related.

**Comment by jsignell** [comment]
Yeah I ended up imposing a bit of structure in the nav: 

image
https://nasa-impact.github.io/veda-docs/example-notebooks/

**Comment by j08lue** [comment]
The notebook I had added to this PR disappeared, unfortunately. It is the NO2 visualization one. We need that for demoing, please.

**Pull request merged**
