### PR TITLE
Fix up downsample-zarr notebook

### LINKED ISSUE #137: Investigate failures in downsample-zarr notebook
There  are some new geoviews failures popping up in downsample-zarr with the latest pangeo image. It seems like they have to do with precomputed holomaps. For now I think it is simpler to workaround the issue by using hvplot rather than geoviews.

### PR DESCRIPTION
**Pull request by jsignell**
- Use cartopy crs directly rather than downgrading hvplot
- Use hvplot rather than geoviews to get around issue with precomputed holomaps (Closes #137)

### CODE REVIEW

**Comment by jsignell** [comment]
<p>Yeah I didn't touch the language in this PR, but these are good thoughts. I can try to make it clearer. It <em>is</em> still using datashader, it's just internal now (via the <code>rasterize</code> kwarg)  </p>

---

 <a href='https://app.reviewnb.com/NASA-IMPACT/veda-docs/pull/139/discussion/#comment-2078328880'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jsignell** [comment]
<p>:+1:</p>

---

 <a href='https://app.reviewnb.com/NASA-IMPACT/veda-docs/pull/139/discussion/#comment-2078328900'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jsignell** [comment]
<p>yeah similar to the datashader it is being used internally, but I agree that in the text needs an update.</p>

---

 <a href='https://app.reviewnb.com/NASA-IMPACT/veda-docs/pull/139/discussion/#comment-2078336197'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jsignell** [comment]
<p>:+1:</p>

---

 <a href='https://app.reviewnb.com/NASA-IMPACT/veda-docs/pull/139/discussion/#comment-2078328910'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jsignell** [comment]
<p>I think aggregate implies that the whole dimension will be collapsed. So I left "coarsening"</p>

---

 <a href='https://app.reviewnb.com/NASA-IMPACT/veda-docs/pull/139/discussion/#comment-2078328880'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jsignell** [comment]
<p>I also decided downsample was correct for the time dimension. I think the name is based off the resample method in xarray (and pandas) then there is "upsample" for when you end up with more values than you started with, and "downsample" for when you end up with fewer. To me subselect should more like taking an aoi or a particular month. More like taking a piece of the data with the existing resolution rather than changing the resolution. Obviously you <em>can</em> use select to change the step, but that's not what first comes to my mind. </p>

---

 <a href='https://app.reviewnb.com/NASA-IMPACT/veda-docs/pull/139/discussion/#comment-2078328880'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jsignell** [comment]
@wildintellect ready for another look

**Review by wildintellect — APPROVED** [review]

**Pull request merged**
