### PR TITLE
Example notebook for using the WFS to visualize fire perimeters

### PR DESCRIPTION
**Pull request by mccabete**
This is a notebook that uses a draft version of the WFS to map fire perimeters.

### CODE REVIEW

**Comment by ranchodeluxe** [comment]
Nice work Tess 🥳 

A couple minor things:

1. Since we don't have our new shiny `conda-store` shared environment thingy up yet (it's in the PI for next quarter) that means we're at the mercy of only being able to run packages that come in the base image. And `owslib` isn't installed.  The simplest and best workaround (though `pip` won't work for all conda packages) is to add a first notebook cell that `pip` installs it in the conda environment. Could you add this first line to the notebook please?

```python
import sys
!{sys.executable} -m pip install OWSLib==0.28.1
```

2. After this merges and once I figure out who has authority to pick a DNS name for the WFS we'll need to change the domain. This shouldn't keep us from merging it. Once that changes I'll put in a follow-up PR 👍

**Comment by ranchodeluxe** [comment]
I tested this out by creating a link from [nbgitpuller](https://hub.jupyter.org/nbgitpuller/link) for SCME

`https://daskhub.veda.smce.nasa.gov/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fmccabete%2Fveda-docs&urlpath=tree%2Fveda-docs%2F%2Fexample-notebooks%2FWFS_workflow_example.ipynb&branch=fire_perimeter_wfs`

**Review by ranchodeluxe — APPROVED** [review]
LGTM! (I used to do engineering that was more closely tied to "sales speak" and whenever I see this acronym I think it means "Let's Go to Market!")

**Comment by mccabete** [comment]
Done! Thanks for the feedback!

**Comment by jsignell** [comment]
> LGTM! (I used to do engineering that was more closely tied to "sales speak" and whenever I see this acronym I think it means "Let's Go to Market!")

Lol I always read it as "legitimate" which I guess would probably be LGTMT actually...

**Pull request merged**
