### PR TITLE
Volcano SO2 monitoring notebook

### PR DESCRIPTION
**Pull request by kathrynberger**
Developed a notebook walking through a previously posted VEDA discovery '[Monitoring Volcanic Sulfur Dioxide Emissions](https://www.earthdata.nasa.gov/dashboard/air-quality/discoveries/so2-volcanoes)' which explored the [Sulfur Dioxide dataset](https://radiantearth.github.io/stac-browser/#/external/staging-stac.delta-backend.com/collections/OMSO2PCA-COG?.language=en). 

The notebook explores three different time-steps to show how NASA has observed volcanic activity in the Galápagos islands (2005), detected large scale emissions on the Kamchatka Peninsula (2009), and monitored the eruptions of Fagradalsfjall in Iceland (2021). These were the three time-steps showcased in the Discovery article. Approach used both the STAC and Raster APIs, and visualized each of these time-steps on a map using `folium`. 

related to: https://github.com/NASA-IMPACT/veda-analytics/issues/46

### CODE REVIEW

**Review by jsignell — APPROVED** [review]
This looks great! Do you want to include it in the table of contents?  I just have one suggestion which is that it is a little strange to keep using the `items[16]` and `items[12]`. Maybe you want to make a dictionary of all the items where the keys are the years. Something like (untested):

```python
items = {item["properties"]["start_datetime"][:4]: item for item in items}
```
Then you can use `items["2005"]` in the rest of the notebook.

**Comment by kathrynberger** [comment]
> This looks great! Do you want to include it in the table of contents? I just have one suggestion which is that it is a little strange to keep using the items[16] and items[12]. Maybe you want to make a dictionary of all the items where the keys are the years. Something like (untested):
> 
> items = {item["properties"]["start_datetime"][:4]: item for item in items} Then you can use items["2005"] in the rest of the notebook.

(apologies, in quoting your reply, I accidentally edited the comment above ☝️) 

Awesome, thanks for the quick review! 💫 
* Yes, that's a great idea, I can add it to the ToC under `datasets` as part of this PR
*  You're right, that's really not the most eloquent way of writing it, I'll revise so that the description of the years is a bit more explicit.

**Comment by kathrynberger** [comment]
@jsignell just implemented the suggestions above (and your untested code works) 🚀 
I've added the notebook to the ToC and I also realized the last tile for Iceland was looking at 2020 and not 2021 - so I've revised it. If you have a few minutes, wouldn't mind your second review before merging. Thanks!

**Comment by jsignell** [comment]
Looks good to me! I will go ahead and merge it.

**Pull request merged**
