### PR TITLE
Add notebook for reading zarr from veda stac catalog and visualizing it

### PR DESCRIPTION
**Pull request by slesaad**
# Changes
- [x] Notebook for reading zarr from veda STAC catalog (dev) and visualizing it
- [x] Added the notebook entry to the "Basics" section

### CODE REVIEW

**Comment by slesaad** [comment]
I noticed in the ReviewNB preview that the map visualization wasn't rendered, does it have to do something with the warning I received about "GH001: Large files detected" ?

Also, the notebook reads data from the dev veda stac catalog, should we wait till the data is published to staging (might take a while) or is it okay to publish this right now and once it's published to staging, update this notebook?

cc @jsignell @ranchodeluxe @abarciauskas-bgse

**Comment by jsignell** [comment]
Yeah I think for now don't worry about the viz not showing up on github. It shows up fine when using nbviewer: https://nbviewer.org/github/NASA-IMPACT/veda-docs/blob/994b71a8e390ecc96aa93e77da65b2ba3b5a92f2/example-notebooks/veda-stac-zarr-viz.ipynb 

Just as a quick question, do you think that this should replace the current visualizing-zarr notebook or I guess more generally how does it relate to that notebook?

**Comment by abarciauskas-bgse** [comment]
I ran the notebook in SMCE and it LGTM!

I defer to you all on if we should remove the existing visualizing-zarr.ipynb notebook - I do think it's helpful to identify some ways to downsample large zarr datasets for visualization but I'm not married to keeping it (especially if it causes confusion to users)

**Comment by slesaad** [comment]
@jsignell @abarciauskas-bgse I did think about updating the existing notebook that aimee created to read from the stac catalog instead of directly from the s3 bucket, but i also think that's it's worth having examples for two different datasets so we can link those from two dataset pages especially since the two zarr datasets are in different projection systems.

**Comment by jsignell** [comment]
Ok! It's really helpful to hear that as a vision. So the current notebooks are kind of more instructional and are intended to demonstrate how to use tools. With that lens on I think this notebook is a clearer example of "how to open and visualize zarr". We can create a new section for more dataset-centric analyses. That is where the old notebook that Aimee wrote can go and that's where the new notebooks that @kathrynberger is writing can go. I can set up that structure and move Aimee's notebook in a separate PR.

**Comment by jsignell** [comment]
@slesaad just let me know if you want to talk my comment over or if you would like me to just push changes to your branch.

**Comment by slesaad** [comment]
@jsignell should i merge this?

**Comment by jsignell** [comment]
> @jsignell should i merge this?

Do you see my review comments?

**Comment by slesaad** [comment]
@jsignell  oof sorry, my mind somehow skipped all those comments from `review-notebook-app` 😅  ; i'll make those changes you mentioned!

**Comment by jsignell** [comment]
No worries at all! And if it's easier I am also happy to take it from here :)

**Comment by slesaad** [comment]
> No worries at all! And if it's easier I am also happy to take it from here :)

you would do that? 🥺  that'd be great! thank you so much ❤️

**Comment by jsignell** [comment]
No problem! I am taking a look now.

**Pull request merged**
