### PR TITLE
Update tutorials notebooks for urls and minor fixes

### PR DESCRIPTION
**Pull request by maxrjones**
This PR updates the tutorials notebooks with openveda.cloud URLS. It also adds `.pre-commit-config.yaml` for linting.

https://github.com/NASA-IMPACT/pangeo-notebook-veda-image/pull/27 along with bumping the image  is required for stac_ipyleaflet to run. There's still an error `'message': 'Error caught with collection', 'error': KeyError('item_assets')` after those fixes, I think I'll need a pointer on how to debug that.

### CODE REVIEW

**Comment by smohiudd** [comment]
@maxrjones I'm only seeing the openveda.cloud update in the zonal statistic notebook. The other notebooks were just rerun/minor updates?

**Comment by smohiudd** [comment]
Where are you seeing `'message': 'Error caught with collection', 'error': KeyError('item_assets')`?

**Comment by maxrjones** [comment]
> @maxrjones I'm only seeing the openveda.cloud update in the zonal statistic notebook. The other notebooks were just rerun/minor updates?

Yeah, I ran through them all and made minor fixes while updating the URLs. I updated the PR title to be more descriptive.

**Comment by maxrjones** [comment]
> Where are you seeing `'message': 'Error caught with collection', 'error': KeyError('item_assets')`?

That was happening when running https://github.com/NASA-IMPACT/veda-docs/blob/main/notebooks/tutorials/stac_ipyleaflet.ipynb with the image from this PR - https://github.com/NASA-IMPACT/pangeo-notebook-veda-image/pull/27.

**Comment by maxrjones** [comment]
> > Where are you seeing `'message': 'Error caught with collection', 'error': KeyError('item_assets')`?
> 
> That was happening when running [`main`/notebooks/tutorials/stac_ipyleaflet.ipynb](https://github.com/NASA-IMPACT/veda-docs/blob/main/notebooks/tutorials/stac_ipyleaflet.ipynb?rgh-link-date=2024-08-16T14%3A15%3A47Z) with the image from this PR - [NASA-IMPACT/pangeo-notebook-veda-image#27](https://github.com/NASA-IMPACT/pangeo-notebook-veda-image/pull/27).

I think it would be best to address this in a separate PR.

**Comment by anayeaye** [comment]
> > Where are you seeing `'message': 'Error caught with collection', 'error': KeyError('item_assets')`?
> 
> That was happening when running https://github.com/NASA-IMPACT/veda-docs/blob/main/notebooks/tutorials/stac_ipyleaflet.ipynb with the image from this PR - [NASA-IMPACT/pangeo-notebook-veda-image#27](https://github.com/NASA-IMPACT/pangeo-notebook-veda-image/pull/27).

I think maybe this needs to be fixed in stac_ipyleaflet https://github.com/MAAP-Project/stac_ipyleaflet/issues/130. I drafted an issue and maybe we can open a PR for it eventually but maybe we should move forward with the other tutorial notebooks?
@maxrjones @smohiudd

**Comment by maxrjones** [comment]
> > > Where are you seeing `'message': 'Error caught with collection', 'error': KeyError('item_assets')`?
> > 
> > 
> > That was happening when running [`main`/notebooks/tutorials/stac_ipyleaflet.ipynb](https://github.com/NASA-IMPACT/veda-docs/blob/main/notebooks/tutorials/stac_ipyleaflet.ipynb?rgh-link-date=2024-08-16T20%3A37%3A05Z) with the image from this PR - [NASA-IMPACT/pangeo-notebook-veda-image#27](https://github.com/NASA-IMPACT/pangeo-notebook-veda-image/pull/27).
> 
> I think maybe this needs to be fixed in stac_ipyleaflet [MAAP-Project/stac_ipyleaflet#130](https://github.com/MAAP-Project/stac_ipyleaflet/issues/130). I drafted an issue and maybe we can open a PR (it looks like a tiny change) for it eventually but maybe we should move forward with the other tutorial notebooks? @maxrjones @smohiudd

Thanks for opening that issue! 💯 on moving forward with the other notebooks

**Review by smohiudd — APPROVED** [review]

**Review by anayeaye — APPROVED** [review]

**Pull request merged**
